### Simplest function

Define a simple function that takes a number and multiplies it by 10:

In [1]:
def multiply_by_ten(x):
    return 10 * x

We can now call this function whenever we need it. Test on some examples:

In [2]:
multiply_by_ten(25)

250

In [3]:
multiply_by_ten(1.2)

12.0

This function works both with integer and real (float) numbers. Python is generally forgiving and will not complain as long as what you're trying to do makes sense.

It's a good practice to include more information about your function. For example, you can add what are the expected types of inputs and outputs (even if the function will work with something else):

In [4]:
def multiply_by_ten(x: float) -> float:
    return 10 * x

It's a very good idea to add a description of what your function does:

In [5]:
def multiply_by_ten(x: float = 10) -> float:
    """Multiplies an integer by 10.
    
    Arguments:
    x: An integer to be multiplied by 10.
    Returns: x multiplied by 10
    """
    return 10 * x

The description is now available when you call help function:

In [6]:
help(multiply_by_ten)

Help on function multiply_by_ten in module __main__:

multiply_by_ten(x: float = 10) -> float
    Multiplies an integer by 10.
    
    Arguments:
    x: An integer to be multiplied by 10.
    Returns: x multiplied by 10



### Numpy arrays

In [7]:
# uncomment and install numpy package if not already installed
# %pip install numpy

In [8]:
# import numpy package
import numpy as np

Define some array for test:

In [9]:
my_array = np.array([0, 1, 2])

Display the array:

In [10]:
my_array

array([0, 1, 2])

The above function multiply_by_ten will already work on arrays:

In [11]:
multiply_by_ten(my_array)

array([ 0, 10, 20])

Numpy will automatically evaluate the function elementwise over the whole array.

Notice that this would not work for lists. Multiplication by 10 means something else for lists -- append the same list 10 times.

In [12]:
my_list = [0, 1, 2]

In [13]:
multiply_by_ten(my_list)

[0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2]

Numpy has implementations of many standard mathematical functions. You can call any of them either on numbers or numpy array. For example:

In [14]:
# squaqre root
np.sqrt(6.25)

2.5

In [15]:
# 4th power
np.power(my_array, 4)

array([ 0,  1, 16])